// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'b8d38441cacbdb69476901187e2efaf66da371d0076be1b8f09acaeb3921dffc'>;
export type ExecutionHash =
  ExecutionHashBase<'43bf20e8bf58a8241ae2535c17f7a6fa8337ffdd5c26007207045c984cb37131'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Agendamento: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly departamento:
        | 'Chefia de Gabinete'
        | 'Secretaria Municipal Governo e Planejamento Estratégico'
        | 'Secretaria Municipal de Assuntos Jurídicos'
        | 'Secretaria Municipal Administração, Gestão e Equipe Públicos'
        | 'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças'
        | 'Secretaria Municipal Turismo, Juventude e Empreendedorismo'
        | 'Secretaria Municipal Obras Públicas'
        | 'Secretaria Municipal Planejamento Urbano e Habitação';
<<<<<<< HEAD
      readonly sala: 'Sala AZul' | 'Sala Verde' | 'Sala Amarela';
=======
      readonly sala: 'Sala Azul' | 'Sala Verde' | 'Sala Amarela';
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
      readonly data: CodecTypes['pg/date-string@1']['output'];
      readonly horaInicio: Varchar<5>;
      readonly horaFim: Varchar<5>;
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Agendamento: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly departamento:
        | 'Chefia de Gabinete'
        | 'Secretaria Municipal Governo e Planejamento Estratégico'
        | 'Secretaria Municipal de Assuntos Jurídicos'
        | 'Secretaria Municipal Administração, Gestão e Equipe Públicos'
        | 'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças'
        | 'Secretaria Municipal Turismo, Juventude e Empreendedorismo'
        | 'Secretaria Municipal Obras Públicas'
        | 'Secretaria Municipal Planejamento Urbano e Habitação';
<<<<<<< HEAD
      readonly sala: 'Sala AZul' | 'Sala Verde' | 'Sala Amarela';
=======
      readonly sala: 'Sala Azul' | 'Sala Verde' | 'Sala Amarela';
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
      readonly data: CodecTypes['pg/date-string@1']['input'];
      readonly horaInicio: CodecTypes['sql/varchar@1']['input'];
      readonly horaFim: CodecTypes['sql/varchar@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly agendamento: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly data: CodecTypes['pg/date-string@1']['output'];
      readonly departamento:
        | 'Chefia de Gabinete'
        | 'Secretaria Municipal Governo e Planejamento Estratégico'
        | 'Secretaria Municipal de Assuntos Jurídicos'
        | 'Secretaria Municipal Administração, Gestão e Equipe Públicos'
        | 'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças'
        | 'Secretaria Municipal Turismo, Juventude e Empreendedorismo'
        | 'Secretaria Municipal Obras Públicas'
        | 'Secretaria Municipal Planejamento Urbano e Habitação';
      readonly horaFim: Varchar<5>;
      readonly horaInicio: Varchar<5>;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
<<<<<<< HEAD
      readonly sala: 'Sala AZul' | 'Sala Verde' | 'Sala Amarela';
=======
      readonly sala: 'Sala Azul' | 'Sala Verde' | 'Sala Amarela';
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly agendamento: {
      readonly criadoEm: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly data: CodecTypes['pg/date-string@1']['input'];
      readonly departamento:
        | 'Chefia de Gabinete'
        | 'Secretaria Municipal Governo e Planejamento Estratégico'
        | 'Secretaria Municipal de Assuntos Jurídicos'
        | 'Secretaria Municipal Administração, Gestão e Equipe Públicos'
        | 'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças'
        | 'Secretaria Municipal Turismo, Juventude e Empreendedorismo'
        | 'Secretaria Municipal Obras Públicas'
        | 'Secretaria Municipal Planejamento Urbano e Habitação';
      readonly horaFim: CodecTypes['sql/varchar@1']['input'];
      readonly horaInicio: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
<<<<<<< HEAD
      readonly sala: 'Sala AZul' | 'Sala Verde' | 'Sala Amarela';
=======
      readonly sala: 'Sala Azul' | 'Sala Verde' | 'Sala Amarela';
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
    };
  };
};

export namespace Models {
  export type public_Agendamento = {
    id: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    departamento:
      | 'Chefia de Gabinete'
      | 'Secretaria Municipal Governo e Planejamento Estratégico'
      | 'Secretaria Municipal de Assuntos Jurídicos'
      | 'Secretaria Municipal Administração, Gestão e Equipe Públicos'
      | 'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças'
      | 'Secretaria Municipal Turismo, Juventude e Empreendedorismo'
      | 'Secretaria Municipal Obras Públicas'
      | 'Secretaria Municipal Planejamento Urbano e Habitação';
<<<<<<< HEAD
    sala: 'Sala AZul' | 'Sala Verde' | 'Sala Amarela';
=======
    sala: 'Sala Azul' | 'Sala Verde' | 'Sala Amarela';
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
    data: CodecTypes['pg/date-string@1']['output'];
    horaInicio: Varchar<5>;
    horaFim: Varchar<5>;
    criadoEm: CodecTypes['pg/timestamptz-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Agendamento: Models.public_Agendamento;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly agendamento: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly departamento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly sala: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly data: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly horaInicio: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 5 };
                };
                readonly horaFim: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 5 };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['sala', 'data', 'horaInicio'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Departamento: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'Chefia de Gabinete',
                'Secretaria Municipal Governo e Planejamento Estratégico',
                'Secretaria Municipal de Assuntos Jurídicos',
                'Secretaria Municipal Administração, Gestão e Equipe Públicos',
                'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças',
                'Secretaria Municipal Turismo, Juventude e Empreendedorismo',
                'Secretaria Municipal Obras Públicas',
                'Secretaria Municipal Planejamento Urbano e Habitação',
              ];
            };
            readonly Sala: {
              readonly kind: 'valueSet';
<<<<<<< HEAD
               readonly values: readonly ['Sala AZul', 'Sala Verde', 'Sala Amarela'];
=======
              readonly values: readonly ['Sala Azul', 'Sala Verde', 'Sala Amarela'];
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly agendamento: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Agendamento';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Agendamento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly departamento: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly sala: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly data: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly horaInicio: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 5 };
                };
              };
              readonly horaFim: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 5 };
                };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'agendamento';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly departamento: { readonly column: 'departamento' };
                readonly sala: { readonly column: 'sala' };
                readonly data: { readonly column: 'data' };
                readonly horaInicio: { readonly column: 'horaInicio' };
                readonly horaFim: { readonly column: 'horaFim' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
        };
        readonly enum: {
          readonly Departamento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CHEFIA_GABINETE'; readonly value: 'Chefia de Gabinete' },
              {
                readonly name: 'SEC_GOVERNO_PLANEJAMENTO';
                readonly value: 'Secretaria Municipal Governo e Planejamento Estratégico';
              },
              {
                readonly name: 'SEC_ASSUNTOS_JURIDICOS';
                readonly value: 'Secretaria Municipal de Assuntos Jurídicos';
              },
              {
                readonly name: 'SEC_ADMINISTRACAO';
                readonly value: 'Secretaria Municipal Administração, Gestão e Equipe Públicos';
              },
              {
                readonly name: 'SEC_FAZENDA';
                readonly value: 'Secretaria Municipal Fazenda, Desenvolvimento Econômico e Finanças';
              },
              {
                readonly name: 'SEC_TURISMO';
                readonly value: 'Secretaria Municipal Turismo, Juventude e Empreendedorismo';
              },
              {
                readonly name: 'SEC_OBRAS_PUBLICAS';
                readonly value: 'Secretaria Municipal Obras Públicas';
              },
              {
                readonly name: 'SEC_PLANEJAMENTO_URBANO';
                readonly value: 'Secretaria Municipal Planejamento Urbano e Habitação';
              },
            ];
          };
          readonly Sala: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
<<<<<<< HEAD
               { readonly name: 'SALA_1'; readonly value: 'Sala AZul' },
               { readonly name: 'SALA_2'; readonly value: 'Sala Verde' },
               { readonly name: 'SALA_3'; readonly value: 'Sala Amarela' },
=======
              { readonly name: 'SALA_1'; readonly value: 'Sala Azul' },
              { readonly name: 'SALA_2'; readonly value: 'Sala Verde' },
              { readonly name: 'SALA_3'; readonly value: 'Sala Amarela' },
>>>>>>> ab0f4558c9df1ae05eb276b326f88b60300fb343
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'agendamento';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
